# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-30 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190330_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 3, 30, 17, 23, 24, 971445), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 3, 30, 17, 23, 24, 972445), verbose_name='Дата'),
        ),
    ]
