# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-20 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190520_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='posted_b',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 5, 20, 12, 18, 23, 382211), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 5, 20, 12, 18, 23, 366611), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 5, 20, 12, 18, 23, 366611), verbose_name='Дата'),
        ),
    ]
